name: Greeting

on: [push, pull_request]

jobs:
    check:
      name: Build & Test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install
          run: |
            sudo apt-get install build-essential cmake
            git clone https://github.com/google/googletest
            cd googletest && mkdir build
            cd build && cmake .. && make
            sudo make install
        - name: Build and Run
          run: make check
          
    release:
      # This job is run only for push events on the main branch
      # Don't forget to change the Workflow Permissions in the Settings of 
      # your repository in Actions > General to Read and Write Permissions
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      name: Make Release
      runs-on: ubuntu-latest
      needs: [check]
      steps:
        - name: Create Release
          uses: crowbarmaster/GH-Automatic-Releases@latest
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            automatic_release_tag: latest
            title: Latest Version
            prerelease: false