name: List

on:
  pull_request:
    branches: 
      - main
  push:
    branches: 
      - '*'

jobs:
  check:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: sudo apt-get install cmake build-essential
      - name: Build and Run Test
        run: |
          mkdir build && cd build && cmake ..
          make && ctest
